name: e2e
on:
  push:
  pull_request:
env:
  ESMETA_HOME: ${{ github.workspace }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Run backend server
      run: sbt "run web"
    - run: curl http://localhost:8080
