name: e2e
on:
  push:
  pull_request:
env:
  ESMETA_HOME: ${{ github.workspace }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Run e2e tests
      run: |
        sbt assembly
        cd $ESMETA_HOME/client 
        npm install
        npx playwright install chromium --with-deps
        npx playwright test --project=chromium
