name: 'esmeta typecheck'

on:
  push:
  pull_request:
env:
  ESMETA_HOME: ${{ github.workspace }}
jobs:
  esmeta-typecheck:
    name: 'esmeta typecheck'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: build esmeta
        run: |
          cd "${ESMETA_HOME}"
          sbt assembly
      - name: typecheck
        run: ./bin/esmeta tycheck -status -tycheck:log
      - name: Archive artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: typecheck logs
          path: |
            logs/analyze/summary.yml
            logs/analyze/errors
