name: gsheet.action test
on: push

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - id: "echo_url"
        run: |
          echo "https://github.com/${{github.repository}}/commit/${{github.sha}}"
      - id: "run_test"
        run: |
          # output date, succeeded, failed, canceled, ignored, pending
          data="[[ \"$(date -I)\", $(sbt test | grep "succeeded" | awk -F'[ ,:]+' '{print "\""$4"\", \""$6"\", \""$8"\",  \""$10"\",  \""$12"\"]]"}')"
          sbt test
          testonly="$(sbt test)"
          echo $testonly
          echo $data
          echo "test_result=$data" >> $GITHUB_ENV
      - id: "update_worksheet"
        uses: jroehl/gsheet.action@v1.0.0 # you can specify '@release' to always have the latest changes
        with:
          spreadsheetId: 1TjIRPE_4jJdAbmOaklSA1ofBBGc6QGu9Bp0muJNYvWI
          commands: | # list of commands, specified as a valid JSON string
            [
              { "command": "getWorksheet", "args": { "worksheetTitle": "report" }},
              { "command": "appendData", "args": { "data": ${{ env.test_result }}, "minCol": 1 }}
            ]
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
